server:
  port: 9004
spring:
  application:
    name: gs-article-9004
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://eventbox-mysql.cu2gba3klpnn.us-west-1.rds.amazonaws.com:3306/gs_recruit?characterEncoding=utf-8&useSSL=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: Qian2012
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 54.183.17.118:6379
  data:
    mongodb:
      host: 54.183.17.118:27017
      database: gs_comment
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true